server:
    servlet:
        context-path: /aoide

spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate.format_sql: true

    data:
        rest:
            base-path: /api
            
# set default profile to 'dev'
    profiles:
        active:
            - dev


