spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:./test
        username: sa
        password: 1234
    jpa:
        hibernate:
            ddl-auto: validate

logging:
    level:
        org.springframework.security: INFO