server:
    servlet:
        context-path: /aoide

spring:
    profiles:  # set default profile to 'dev'
        active:
            - dev
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate.format_sql: true

    data:
        rest:
            base-path: /api
            

    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: clientId
                        clientSecret: github-client-secret


